version: '3.8'

services:
  inbibe_bot:
    build: .
    environment:
      - api_key=${API_KEY}
      - admin_group_id=${ADMIN_GROUP_ID}
    restart: always

    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "64M"
        reservations:
          cpus: "0.05"
          memory: "64M"
